// <auto-generated />
using System;
using AutoScrew.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoScrew.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810022426_AddLockRecordHostIdentity")]
    partial class AddLockRecordHostIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.ErrorLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LockRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolveBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolveTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockRecordId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.LockRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostMac")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRework")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("StartedAt");

                    b.ToTable("LockRecords");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.OutboxUploadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("SentAt");

                    b.ToTable("OutboxUploads");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.ProductTemplateSyncEntity", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMesPullUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMesPushUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LocalModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MesRevision")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartNumber");

                    b.HasIndex("SyncState");

                    b.ToTable("ProductTemplateSyncs");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.ScrewDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurvePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalAngleDeg")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinalTorqueNm")
                        .HasColumnType("REAL");

                    b.Property<long>("LockRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockRecordId");

                    b.ToTable("ScrewDetails");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.SessionCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionCheckpoints");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.SnJobMemoryEntity", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SnJobMemories");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.UserAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Category");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
