// <auto-generated />
using System;
using AutoScrew.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoScrew.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.ErrorLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LockRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolveBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolveTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockRecordId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.LockRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRework")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("StartedAt");

                    b.ToTable("LockRecords");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.OutboxUploadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("SentAt");

                    b.ToTable("OutboxUploads");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.ScrewDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurvePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalAngleDeg")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinalTorqueNm")
                        .HasColumnType("REAL");

                    b.Property<long>("LockRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockRecordId");

                    b.ToTable("ScrewDetails");
                });

            modelBuilder.Entity("AutoScrew.Infrastructure.Persistence.SessionCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionCheckpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
