#!/usr/bin/env python3
"""Extract IEMD-SD Modbus function codes from EN manual PDF and generate catalog artifacts."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PDF = ROOT / "doc" / "DELTA_IA-DCSS_SD3_UM_EN_20260310.pdf"
JSON_OUT = ROOT / "tools" / "iemd_modbus_catalog.json"
MD_OUT = ROOT / "doc" / "IEMD_SD_MODBUS_COMMANDS.md"
CS_ENUM = ROOT / "src" / "UDL.Delta.IemdSd" / "Modbus" / "ModbusFunctionCode.g.cs"
CS_CATALOG = ROOT / "src" / "UDL.Delta.IemdSd" / "Modbus" / "ModbusCommandCatalog.g.cs"

WRITE_THEN_MAILBOX = {
    100, 101, 200, 201, 202, 203, 301, 512, 513,
}
MAILBOX_THEN_READ = {
    150, 160, 250, 251, 252, 253, 260, 350, 351, 450, 451, 452, 453,
    550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562,
    563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576,
    577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587,
    650, 651, 652, 653, 655, 656, 657, 658, 659, 660, 661,
    750, 751, 752, 753, 754, 760,
}
TYPICAL_WORD_COUNT = {
    100: 349, 150: 349, 750: 253, 751: 150,
}

def extract_codes() -> list[dict]:
    from pypdf import PdfReader

    r = PdfReader(str(PDF))
    seen: dict[int, str] = {}
    for i in range(min(50, len(r.pages))):
        t = r.pages[i].extract_text() or ""
        for m in re.finditer(
            r"#(\d{3})\s+([^#\n]+?)(?=\s+#\d{3}|\s*\.{3,}|\s+[AB]-\d+|\n|$)", t
        ):
        if m.group(2).strip().startswith("Add the function codes"):
            continue
            code = int(m.group(1))
            name = re.sub(r"[\s\.]+$", "", m.group(2).strip())
            name = re.sub(r"\s+", " ", name)
            if len(name) >= 8:
                seen[code] = name

    for i, p in enumerate(r.pages):
        t = p.extract_text() or ""
        for m in re.finditer(r"^#(\d{3})\s+([A-Za-z].+)$", t, re.MULTILINE):
            code = int(m.group(1))
            name = m.group(2).strip()
            if 100 <= code <= 760:
                seen[code] = name

    return [{"code": c, "name": seen[c]} for c in sorted(seen)]


def classify(name: str, code: int) -> tuple[str, str]:
    lower = name.lower()
    if lower.startswith("read") or lower.startswith("find and read"):
        direction = "Read"
    elif lower.startswith("clear"):
        direction = "Write"
    else:
        direction = "Write"
    if code in WRITE_THEN_MAILBOX:
        payload = "WriteThenMailbox"
    elif code in MAILBOX_THEN_READ:
        payload = "MailboxThenRead"
    elif code == 562:
        payload = "MailboxThenReadCommandRequest"
    else:
        payload = "MailboxOnly"
    return direction, payload


def to_enum_member(code: int, name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", name)
    slug = re.sub(r"_+", "_", slug).strip("_")
    if slug and slug[0].isdigit():
        slug = "Cmd_" + slug
    if not slug:
        slug = f"Command_{code}"
    # shorten
    parts = [p for p in slug.split("_") if p and p.lower() not in {"the", "to", "a", "of", "for", "and"}]
    slug = "_".join(parts[:6]) or f"Command_{code}"
    return f"    {slug} = {code},"


def main() -> None:
    items = extract_codes()
    JSON_OUT.write_text(json.dumps(items, indent=2), encoding="utf-8")

    md_lines = [
        "# IEMD-SD Modbus Function Code Catalog",
        "",
        "Source: [DELTA_IA-DCSS_SD3_UM_EN_20260310.pdf](DELTA_IA-DCSS_SD3_UM_EN_20260310.pdf) Appendix A/B.",
        f"Generated by `tools/generate_iemd_modbus_catalog.py`. **{len(items)}** unique function codes.",
        "",
        "| Code | Name | Direction | Payload | Typical words |",
        "|------|------|-----------|---------|---------------|",
    ]
    enum_lines = [
        "// <auto-generated />",
        "namespace UDL.Delta.IemdSd.Modbus;",
        "",
        "/// <summary>Delta IEMD-SD mailbox function codes (manual Appendix A/B).</summary>",
        "public enum ModbusFunctionCode",
        "{",
    ]
    catalog_entries = []

    for item in items:
        code = item["code"]
        name = item["name"]
        direction, payload = classify(name, code)
        words = TYPICAL_WORD_COUNT.get(code)
        word_str = str(words) if words else "—"
        md_lines.append(f"| #{code} | {name} | {direction} | {payload} | {word_str} |")
        enum_lines.append(to_enum_member(code, name))
        esc_name = name.replace('"', '\\"')
        catalog_entries.append(
            f'        [{code}] = new ModbusCommandDescriptor({code}, "{esc_name}", '
            f'ModbusCommandDirection.{direction}, ModbusCommandPayloadKind.{payload}, '
            f'{(str(words) + "u") if words else "null"}),'
        )

    enum_lines.append("}")
    CS_ENUM.write_text("\n".join(enum_lines) + "\n", encoding="utf-8")

    catalog_cs = """// <auto-generated />
namespace UDL.Delta.IemdSd.Modbus;

public static partial class ModbusCommandCatalog
{
    public static IReadOnlyDictionary<int, ModbusCommandDescriptor> All { get; } =
        new Dictionary<int, ModbusCommandDescriptor>
        {
"""
    catalog_cs += "\n".join(catalog_entries)
    catalog_cs += """
        };

    public static bool TryGet(int code, out ModbusCommandDescriptor descriptor) =>
        All.TryGetValue(code, out descriptor!);

    public static ModbusCommandDescriptor Get(int code) =>
        All.TryGetValue(code, out var d)
            ? d
            : throw new KeyNotFoundException($"Unknown Modbus function code #{code}.");
}
"""
    CS_CATALOG.write_text(catalog_cs, encoding="utf-8")
    MD_OUT.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    print(f"Generated {len(items)} codes -> {MD_OUT.name}")


if __name__ == "__main__":
    main()
